// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Michael Fiedler     - initial API and implementation for Bugzilla adapter
 *     Jad El-khoury       - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *     Jim Amsden          - Support for UI Preview (494303)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package hon.oslc.automation.services;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.FormParam;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.core.UriBuilder;

import org.apache.wink.json4j.JSONObject;
import org.eclipse.lyo.oslc4j.provider.json4j.JsonHelper;
import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.annotation.OslcCreationFactory;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialog;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialogs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcQueryCapability;
import org.eclipse.lyo.oslc4j.core.annotation.OslcService;
import org.eclipse.lyo.oslc4j.core.model.Compact;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.OslcMediaType;
import org.eclipse.lyo.oslc4j.core.model.Preview;
import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;

import hon.oslc.automation.AdapterManager;
import hon.oslc.automation.AdapterConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import org.eclipse.lyo.oslc.domains.auto.Oslc_autoDomainConstants;
import hon.oslc.automation.servlet.ServiceProviderCatalogSingleton;
import org.eclipse.lyo.oslc.domains.auto.AutomationPlan;
import org.eclipse.lyo.oslc.domains.auto.AutomationRequest;
import org.eclipse.lyo.oslc.domains.auto.AutomationResult;
import hon.oslc.automation.resources.Measure;
import org.eclipse.lyo.oslc.domains.auto.ParameterDefinition;
import org.eclipse.lyo.oslc.domains.auto.ParameterInstance;
import org.eclipse.lyo.oslc.domains.Person;

// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code
@OslcService(Oslc_autoDomainConstants.AUTOMATION_DOMAIN)
@Path("serviceProviders/{serviceProviderId}/resources")
public class ServiceProviderService1
{
    @Context private HttpServletRequest httpServletRequest;
    @Context private HttpServletResponse httpServletResponse;
    @Context private UriInfo uriInfo;

    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    // End of user code

    public ServiceProviderService1()
    {
        super();
    }

    @OslcQueryCapability
    (
        title = "AutoPlanQueryCapability",
        label = "AutoPlanQueryCapability",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONPLAN_PATH,
        resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONPLAN_TYPE},
        usages = {}
    )
    @GET
    @Path("queryAutoPlan")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationPlan[] queryAutomationPlans(
                                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationPlans
        // Here additional logic can be implemented that complements main action taken in AdapterManager
        // End of user code

        final List<AutomationPlan> resources = AdapterManager.queryAutomationPlans(httpServletRequest, serviceProviderId, where, page, limit);
        return resources.toArray(new AutomationPlan [resources.size()]);
    }

    @GET
    @Path("queryAutoPlan")
    @Produces({ MediaType.TEXT_HTML })
    public Response queryAutomationPlansAsHtml(
                                    @PathParam("serviceProviderId") final String serviceProviderId ,
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryAutomationPlansAsHtml
        // End of user code

        final List<AutomationPlan> resources = AdapterManager.queryAutomationPlans(httpServletRequest, serviceProviderId, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code queryAutomationPlansAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationplanscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    /**
     * Create a single AutomationPlan via RDF/XML, XML or JSON POST
     *
     * @throws IOException
     * @throws ServletException
     */
    @OslcCreationFactory
    (
         title = "AutoPlanCreationFactory",
         label = "AutoPlanCreationFactory",
         resourceShapes = {OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONPLAN_PATH},
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONPLAN_TYPE},
         usages = {}
    )
    @POST
    @Path("createAutoPlan")
    @Consumes({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public Response createAutomationPlan(
            @PathParam("serviceProviderId") final String serviceProviderId ,
            final AutomationPlan aResource
        ) throws IOException, ServletException
    {
        try {
            AutomationPlan newResource = AdapterManager.createAutomationPlan(httpServletRequest, aResource, serviceProviderId);
            httpServletResponse.setHeader("ETag", AdapterManager.getETagFromAutomationPlan(newResource));
            return Response.created(newResource.getAbout()).entity(newResource).header(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2).build();
        } catch (Exception e) {
            e.printStackTrace();
            throw new WebApplicationException(e);
        }
    }

    /**
     * Create a single AutomationRequest via RDF/XML, XML or JSON POST
     *
     * @throws IOException
     * @throws ServletException
     */
    @OslcCreationFactory
    (
         title = "AutoReqCreationFactory",
         label = "AutoReqCreationFactory",
         resourceShapes = {OslcConstants.PATH_RESOURCE_SHAPES + "/" + Oslc_autoDomainConstants.AUTOMATIONREQUEST_PATH},
         resourceTypes = {Oslc_autoDomainConstants.AUTOMATIONREQUEST_TYPE},
         usages = {}
    )
    @POST
    @Path("createAutoReq")
    @Consumes({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public Response createAutomationRequest(
            @PathParam("serviceProviderId") final String serviceProviderId ,
            final AutomationRequest aResource
        ) throws IOException, ServletException
    {
        try {
            AutomationRequest newResource = AdapterManager.createAutomationRequest(httpServletRequest, aResource, serviceProviderId);
            httpServletResponse.setHeader("ETag", AdapterManager.getETagFromAutomationRequest(newResource));
            return Response.created(newResource.getAbout()).entity(newResource).header(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2).build();
        } catch (Exception e) {
            e.printStackTrace();
            throw new WebApplicationException(e);
        }
    }

    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationPlan getAutomationPlan(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationPlan aAutomationPlan = AdapterManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            // Start of user code getAutomationPlan
            // End of user code
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            return aAutomationPlan;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationPlanAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtml_init
        // End of user code

        final AutomationPlan aAutomationPlan = AdapterManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationplan.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationPlanCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationPlanCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationPlan aAutomationPlan = AdapterManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationPlan.getAbout());
            compact.setTitle(aAutomationPlan.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationPlan.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationPlan.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationPlanAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtmlSmallPreview_init
        // End of user code

        final AutomationPlan aAutomationPlan = AdapterManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationplansmallpreview.jsp");
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationPlans/{automationPlanId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationPlanAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationPlanId") final String automationPlanId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationPlanAsHtmlLargePreview_init
        // End of user code

        final AutomationPlan aAutomationPlan = AdapterManager.getAutomationPlan(httpServletRequest, serviceProviderId, automationPlanId);

        if (aAutomationPlan != null) {
            httpServletRequest.setAttribute("aAutomationPlan", aAutomationPlan);
            // Start of user code getAutomationPlanAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationplanlargepreview.jsp");
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationRequest getAutomationRequest(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationRequest aAutomationRequest = AdapterManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            // Start of user code getAutomationRequest
            // End of user code
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            return aAutomationRequest;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationRequestAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtml_init
        // End of user code

        final AutomationRequest aAutomationRequest = AdapterManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationrequest.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationRequestCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationRequestCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationRequest aAutomationRequest = AdapterManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationRequest.getAbout());
            compact.setTitle(aAutomationRequest.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationRequest.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationRequest.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationRequestAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtmlSmallPreview_init
        // End of user code

        final AutomationRequest aAutomationRequest = AdapterManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationrequestsmallpreview.jsp");
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationRequests/{automationRequestId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationRequestAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationRequestId") final String automationRequestId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationRequestAsHtmlLargePreview_init
        // End of user code

        final AutomationRequest aAutomationRequest = AdapterManager.getAutomationRequest(httpServletRequest, serviceProviderId, automationRequestId);

        if (aAutomationRequest != null) {
            httpServletRequest.setAttribute("aAutomationRequest", aAutomationRequest);
            // Start of user code getAutomationRequestAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationrequestlargepreview.jsp");
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON, OslcMediaType.TEXT_TURTLE})
    public AutomationResult getAutomationResult(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final AutomationResult aAutomationResult = AdapterManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            // Start of user code getAutomationResult
            // End of user code
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            return aAutomationResult;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getAutomationResultAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtml_init
        // End of user code

        final AutomationResult aAutomationResult = AdapterManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationresult.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getAutomationResultCompact(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getAutomationResultCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final AutomationResult aAutomationResult = AdapterManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            final Compact compact = new Compact();

            compact.setAbout(aAutomationResult.getAbout());
            compact.setTitle(aAutomationResult.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aAutomationResult.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(UriBuilder.fromUri(aAutomationResult.getAbout()).path("largePreview").build());
            compact.setLargePreview(largePreview);

            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationResultAsHtmlSmallPreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtmlSmallPreview_init
        // End of user code

        final AutomationResult aAutomationResult = AdapterManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationresultsmallpreview.jsp");
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("automationResults/{automationResultId}/largePreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getAutomationResultAsHtmlLargePreview(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("automationResultId") final String automationResultId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getAutomationResultAsHtmlLargePreview_init
        // End of user code

        final AutomationResult aAutomationResult = AdapterManager.getAutomationResult(httpServletRequest, serviceProviderId, automationResultId);

        if (aAutomationResult != null) {
            httpServletRequest.setAttribute("aAutomationResult", aAutomationResult);
            // Start of user code getAutomationResultAsHtmlLargePreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/hon/oslc/automation/automationresultlargepreview.jsp");
            httpServletResponse.addHeader(AdapterConstants.HDR_OSLC_VERSION, AdapterConstants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
}
