// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package hon.oslc.automation;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;

// Start of user code imports
// End of user code

public class AdapterConstants
{
    // Start of user code user constants


	/**
	 * Updates the "constants" that are loaded from a .properties file
	 */
	static void updateConstants()
	{
		ADAPTER_URL = ADAPTER_HOST + ":" + ADAPTER_PORT + "/";
	    PATH_AUTOMATION_SERVICE_PROVIDERS = ADAPTER_URL + ADAPTER_CONTEXT + "services/serviceProviders/";
        PATH_RESOURCE_SHAPES = ADAPTER_URL + ADAPTER_CONTEXT + "services/resourceShapes/";
        
        VERIFY_URL = VERIFY_HOST + ":" + VERIFY_PORT + "/";
	}

	/*
	 *  Java properties constants - loaded from the .properties file on startup, and constant after
	 */
	public static final String PROPERTIES_PATH = "./adapter.properties";

	public static String ADAPTER_HOST;
    public static String ADAPTER_PORT;
    
	public static String VERIFY_HOST;
	public static String VERIFY_PORT;

    public static String SPARQL_SERVER_QUERY_ENDPOINT;
    public static String SPARQL_SERVER_UPDATE_ENDPOINT;
    
    // these three are derived from the values in .properties
	public static String ADAPTER_URL;
	public static String VERIFY_URL;
    public static String PATH_AUTOMATION_SERVICE_PROVIDERS;
    public static String PATH_RESOURCE_SHAPES;
    
    
    /*
     *  Internal constants - actually constant at all times
     */
	public static final String ADAPTER_CONTEXT = "adapter/";
	public static final String AUTOMATION_PROVIDER_ID = "A0";
	
	
	/*
	 * OSLC defined constants - copied from the specification
	 */
	
    public static final String AUTOMATION_STATE_NEW = "http://open-services.net/ns/auto#success";
    public static final String AUTOMATION_STATE_QUEUED = "http://open-services.net/ns/auto#queued";
    public static final String AUTOMATION_STATE_INPROGRESS = "http://open-services.net/ns/auto#inProgress";
    public static final String AUTOMATION_STATE_CANCELING = "http://open-services.net/ns/auto#canceling";
    public static final String AUTOMATION_STATE_CANCELED = "http://open-services.net/ns/auto#canceled";
    public static final String AUTOMATION_STATE_COMPLETE = "http://open-services.net/ns/auto#complete";
    
    public static final String AUTOMATION_VERDICT_UNAVAILABLE = "http://open-services.net/ns/auto#unavailable";
    public static final String AUTOMATION_VERDICT_PASSED = "http://open-services.net/ns/auto#passed";
    public static final String AUTOMATION_VERDICT_WARNING = "http://open-services.net/ns/auto#warning";
    public static final String AUTOMATION_VERDICT_FAILED = "http://open-services.net/ns/auto#failed";
    public static final String AUTOMATION_VERDICT_ERROR = "http://open-services.net/ns/auto#error";

    public static final String OSLC_OCCURS_ZEROorONE = "http://open-services.net/ns/core#Zero-or-One";
    public static final String OSLC_OCCURS_ONE = "http://open-services.net/ns/core#Exactly-one";
    public static final String OSLC_OCCURS_ZEROorMany = "http://open-services.net/ns/core#Zero-or-many";
    public static final String OSLC_OCCURS_ONEorMany = "http://open-services.net/ns/core#One-or-many";
    
    // ADD more value types when needed
    // https://archive.open-services.net/bin/view/Main/OSLCCoreSpecAppendixA.html#Value_type_Property
    public static final String OSLC_VAL_TYPE_STRING = "http://www.w3.org/2001/XMLSchema#string";
    
    // ADD more value types when needed
    // https://archive.open-services.net/bin/view/Main/OSLCCoreSpecAppendixA.html#Representation_Property
    public static final String OSLC_REPRESENTATION_EITHER = "http://open-services.net/ns/core#Either";
    
    public static final String SPARQL_SERVER_NAMED_GRAPH_RESOURCES = "http://automation_resources";
    
    // End of user code

    public static final String HDR_OSLC_VERSION = "OSLC-Core-Version";
    public static final String OSLC_VERSION_V2 = "2.0";
}
